### ISSUE TITLE
unable to update or preview selected polygon

### ISSUE THREAD

**Issue by IbrahemElanany** [moathdev/laravel-nova-polygon-map-field#2]
i tried to save map field value as string or json but i could not preview or edit that polygon .

**Comment by moathdev** [comment]
@IbrahemElanany Share the PHP, laravel, database versions?

**Comment by IbrahemElanany** [comment]
PHP 7.4.21
"laravel/framework": "^8.40"
Database : MYSQL
----------------------------------------------------
The code in nova resource : 
`Polygon::make('Locations','district_locations'),`
----------------------------------------------------
The column in db is text type
[https://i.imgur.com/PZM8phS.png](url)

**Comment by IbrahemElanany** [comment]
data saved successfully but not previewed
That is the data format saved
https://i.imgur.com/MNJMLjS.png

**Comment by IbrahemElanany** [comment]
Solved , just i need to decode the retrieved data.
Thanks
